authors: [ChillerCraft, NoRC, Feaelin]
description: Community Bridging plugin based off of ChillerCrafts ForumBridge plugin
name: CommunityBridge
website: http://dev.bukkit.org/server-mods/communitybridge-fm/
version: 1.12.0

softdepend: [bPermissions, GroupManager, PermissionsBukkit, PermissionsEx]
main: net.netmanagers.community.Main

# Note 'usage:' is commented out because as of Bukkit 1.3.1-R2, the message
# is displayed without the plugin prefix. If this is changed, then a developer
# can uncomment these and remove the then redundant else's in onCommand.
# Unfortunately, I was later told this behavior will not change...
commands:
  cbban:
    description: Bans from the forum.
    #usage: "밖Incorrect usage, use: /cbban <username>"
    permission: communitybridge.cbban
    permission-message: "밖You do not have access to that command."
  cbunban:
    description: Unbans from the forum.
    #usage: "밖Incorrect usage, use: /cbunban <username>"
    permission: communitybridge.cbunban
    permission-message: "밖You do not have access to that command."
  cbrank:
    description: Ranks on the forum.
    #usage: "밖Incorrect usage, use: /cbrank <username> <rank>"
    permission: communitybridge.cbrank
    permission-message: "밖You do not have access to that command."
  cbsync:
    description: Syncs to the forum.
    #usage: "밖Incorrect usage, use: /cbsync"
    permission: communitybridge.cbsync
    permission-message: "밖You do not have access to that command."
  cbsyncall:
    description: Syncs everyone to the forum.
    #usage: "밖Incorrect usage, use: /cbsyncall"
    permission: communitybridge.cbsyncall
    permission-message: "밖You do not have access to that command."

permissions:
  communitybridge.*:
    description: Grants access to all CommunityBridge commands
    children:
      communitybridge.cbban: true
      communitybridge.cbrank: true
      communitybridge.cbsync: true
      communitybridge.cbsyncall: true
      communitybridge.cbunban: true
  communitybridge.cbban:
    description: Allows use of the /cbban command.
    default: op
  communitybridge.cbunban:
    description: Allows use of the /cbunban command.
    default: op
  communitybridge.cbrank:
    description: Allows use of the /cbrank command.
    default: op
  communitybridge.cbsync:
    description: Allows use of the /cbsync command.
    default: true
  communitybridge.cbsyncall:
    description: Allows use of the /cbsyncall command.
    default: op